import { FastifyRequest, FastifyReply } from "fastify";
import z  from "zod";
import { EmailExists } from "@/error/error";
import { createUser } from "../factory/user";

export async function userController(request: FastifyRequest, reply: FastifyReply){
      
    const registerBodySchema = z.object({
        name: z.string({required_error: "Name is require"}),
        email: z.string({required_error: "Email is require"}).email().min(6),
        password: z.string().min(6),
        bornDate:  z.string().refine(value => {
            // Validação básica de formato
            return /^\d{2}\/\d{2}\/\d{4}$/.test(value);
          }, {
            message: "Date must be in the format dd/mm/yyyy",
          }).transform(value => {
            // Transformando a string no formato dd/mm/yyyy para um objeto Date
            const [day, month, year] = value.split('/');
            return new Date(`${year}-${month}-${day}`);
          }), 
        expertise: z.enum([ 
            "FRONTEND_DEVELOPER",
            "BACKEND_DEVELOPER",
            "FULLSTACK_DEVELOPER",
            "UI_UX_DESIGNER",
            "GRAPHIC_DESIGNER",
            "DATA_SCIENTIST",
            "DEVOPS",
            "MOBILE_DEVELOPER",
            "SECURITY_ENGINEER",
            "CLOUD_ENGINEER",
            "AI_ML_ENGINEER",
            "GAME_DEVELOPER",
            "DATABASE_ADMINISTRATOR",
            "PRODUCT_MANAGER",
            "SYSTEM_ARCHITECT",
            "IT_SUPPORT",
            "Programmer"
        ]).default("Programmer"),
        country: z.enum([
          'AFGHANISTAN',
          'ALBANIA',
          'ALGERIA',
          'ANDORRA',
          'ANGOLA',
          'ARGENTINA',
          'ARMENIA',
          'AUSTRALIA',
          'AUSTRIA',
          'AZERBAIJAN',
          'BAHAMAS',
          'BAHRAIN',
          'BANGLADESH',
          'BARBADOS',
          'BELARUS',
          'BELGIUM',
          'BELIZE',
          'BENIN',
          'BHUTAN',
          'BOLIVIA',
          'BOSNIA_AND_HERZEGOVINA',
          'BOTSWANA',
          'BRAZIL',
          'BRUNEI',
          'BULGARIA',
          'BURKINA_FASO',
          'BURUNDI',
          'CABO_VERDE',
          'CAMBODIA',
          'CAMEROON',
          'CANADA',
          'CHAD',
          'CHILE',
          'CHINA',
          'COLOMBIA',
          'COMOROS',
          'COSTA_RICA',
          'CROATIA',
          'CUBA',
          'CYPRUS',
          'CZECH_REPUBLIC',
          'DENMARK',
          'DJIBOUTI',
          'DOMINICA',
          'DOMINICAN_REPUBLIC',
          'ECUADOR',
          'EGYPT',
          'EL_SALVADOR',
          'EQUATORIAL_GUINEA',
          'ERITREA',
          'ESTONIA',
          'ESWATINI',
          'ETHIOPIA',
          'FIJI',
          'FINLAND',
          'FRANCE',
          'GABON',
          'GAMBIA',
          'GEORGIA',
          'GERMANY',
          'GHANA',
          'GREECE',
          'GRENADA',
          'GUATEMALA',
          'GUINEA',
          'GUINEA_BISSAU',
          'GUYANA',
          'HAITI',
          'HONDURAS',
          'HUNGARY',
          'ICELAND',
          'INDIA',
          'INDONESIA',
          'IRAN',
          'IRAQ',
          'IRELAND',
          'ISRAEL',
          'ITALY',
          'IVORY_COAST',
          'JAMAICA',
          'JAPAN',
          'JORDAN',
          'KAZAKHSTAN',
          'KENYA',
          'KIRIBATI',
          'KOREA_NORTH',
          'KOREA_SOUTH',
          'KUWAIT',
          'KYRGYZSTAN',
          'LAOS',
          'LATVIA',
          'LEBANON',
          'LESOTHO',
          'LIBERIA',
          'LIBYA',
          'LIECHTENSTEIN',
          'LITHUANIA',
          'LUXEMBOURG',
          'MADAGASCAR',
          'MALAWI',
          'MALAYSIA',
          'MALDIVES',
          'MALI',
          'MALTA',
          'MAURITANIA',
          'MAURITIUS',
          'MEXICO',
          'MICRONESIA',
          'MOLDOVA',
          'MONACO',
          'MONGOLIA',
          'MONTENEGRO',
          'MOROCCO',
          'MOZAMBIQUE',
          'MYANMAR',
          'NAMIBIA',
          'NAURU',
          'NEPAL',
          'NETHERLANDS',
          'NEW_ZEALAND',
          'NICARAGUA',
          'NIGER',
          'NIGERIA',
          'NORTH_MACEDONIA',
          'NORWAY',
          'OMAN',
          'PAKISTAN',
          'PALAU',
          'PALESTINE',
          'PANAMA',
          'PAPUA_NEW_GUINEA',
          'PARAGUAY',
          'PERU',
          'PHILIPPINES',
          'POLAND',
          'PORTUGAL',
          'QATAR',
          'ROMANIA',
          'RUSSIA',
          'RWANDA',
          'SAINT_KITTS_AND_NEVIS',
          'SAINT_LUCIA',
          'SAINT_VINCENT_AND_THE_GRENADINES',
          'SAMOA',
          'SAN_MARINO',
          'SAO_TOME_AND_PRINCIPE',
          'SAUDI_ARABIA',
          'SENEGAL',
          'SERBIA',
          'SEYCHELLES',
          'SIERRA_LEONE',
          'SINGAPORE',
          'SLOVAKIA',
          'SLOVENIA',
          'SOLOMON_ISLANDS',
          'SOMALIA',
          'SOUTH_AFRICA',
          'SOUTH_SUDAN',
          'SPAIN',
          'SRI_LANKA',
          'SUDAN',
          'SURINAME',
          'SWEDEN',
          'SWITZERLAND',
          'SYRIA',
          'TAIWAN',
          'TAJIKISTAN',
          'TANZANIA',
          'THAILAND',
          'TIMOR_LESTE',
          'TOGO',
          'TONGA',
          'TRINIDAD_AND_TOBAGO',
          'TUNISIA',
          'TURKEY',
          'TURKMENISTAN',
          'TUVALU',
          'UGANDA',
          'UKRAINE',
          'UNITED_ARAB_EMIRATES',
          'UNITED_KINGDOM',
          'UNITED_STATES',
          'URUGUAY',
          'UZBEKISTAN',
          'VANUATU',
          'VATICAN_CITY',
          'VENEZUELA',
          'VIETNAM',
          'YEMEN',
          'ZAMBIA',
          'ZIMBABWE',
        ]).default("ANGOLA"),
        gender: z.enum(["MALE","FEMALE"])
    });

    const {name, email, bornDate, country, expertise, gender, password } = registerBodySchema.parse(request.body);

      
    try {
      const registerUserUsecase = createUser()
      await registerUserUsecase.execute({
          name,
          email, 
          password,
          bornDate,
          country,
          expertise, 
          gender,
      });

  } catch (err) {
      if(err instanceof EmailExists){
          return reply.status(409).send({message: err.message});
      }
      throw err
  }

  return reply.status(201).send("Cadastro bem sucedido, seja bem-vindo ✔");
}